[server]
port = "8080"

[db]
host = "localhost"
post = 5432
name = "btc-bridge"
user = "aurauser"
password = "aurapassword"

[bitcoin]
network = "tesnet3"
host = "103.154.187.179:18332"
user = "user"
password = "123@abcD"
query-interval = 60
min-confirms = 3

[evm]
url = "https://jsonrpc.dev.aura.network/"
chain-id = 1235
query-interval = 6
min-confirms = 1
private-key = "ef716c789ee010efb4efb245bb5e5ce5d734aedb7753289ea09e146ecf30e88f"
call-timeout = 10

[evm.contracts]
wrapped-btc-addr = "0x7fd84b9a10f13acD07B9fA95D217827dCf608140"
gateway-addr = "0x6731881DE07Ffce55968a583F5f641C589d25ea7"

# Address of bitcoin multsig wallet
bitcoin-multisig = "tb1qqgnkrkhkeql9n2ear5z2c3t49496t6ca0r5ckj"
