[server]
port = "8080"

[db]
host = "localhost"
post = 5432
name = "btc-bridge"
user = "aurauser"
password = "aurapassword"

[bitcoin]
network = "tesnet3"
host = "103.154.187.179:18332"
user = "user"
password = "123@abcD"
query-interval = 60
min-confirms = 3

[evm]
url = "https://evmos-testnet-jsonrpc.alkadeta.com"
chain-id = 9000
query-interval = 30
min-confirms = 5
private-key = "883d80012adf2272875981428715c56558eb388dcea4b48e030bd63ddd23c128"
call-timeout = 10

[evm.contracts]
wrapped-btc-addr = "0x7fd84b9a10f13acD07B9fA95D217827dCf608140"
gateway-addr = "0x6731881DE07Ffce55968a583F5f641C589d25ea7"

# Address of bitcoin multsig wallet
bitcoin-multisig = "tb1qqgnkrkhkeql9n2ear5z2c3t49496t6ca0r5ckj"
