[server]
port = "8080"

[db]
host = "localhost"
post = 5432
name = "btc-bridge"
user = "aurauser"
password = "aurapassword"

[bitcoin]
network = "tesnet3"
host = "103.154.187.179:18332"
user = "user"
password = "123@abcD"
interval = 10

[evm]
url = "https://evmos-testnet-jsonrpc.alkadeta.com"
chain-id = 1
interval = 30

[[operators]]
evm-address = "0xC32B94C38bbbfe65eCe90daF3493c7603dA2c19A"
grpc-url = "127.0.0.1:5055"

# [[operators]]
# evm-address = "0x778Daaec5D30e03367c53eAcC845f9cBF5E931BF"
# grpc-url = "127.0.0.1:5056"

# [[operators]]
# evm-address = "0x1f703E98E188564C971F5ac6DC32786fc6973749"
# grpc-url = "127.0.0.1:5057"

# Add more operators if needed

# Address of bitcoin multsig wallet
bitcoin-multisig = "tb1qqgnkrkhkeql9n2ear5z2c3t49496t6ca0r5ckj"
