[server]
port = "8080"

[db]
host = "localhost"
post = 5432
name = "btc-bridge"
user = "aurauser"
password = "aurapassword"

[bitcoin]
network = "tesnet3"
host = "103.154.187.179:18332"
user = "user"
password = "123@abcD"
interval = 10

[evm]
url = "https://evmos-testnet-jsonrpc.alkadeta.com"
chain-id = 1
interval = 30

[[operators]]
evm-address = "0xYourEvmAddress1"
grpc-url = "127.0.0.1:5055"

# [[operators]]
# evm-address = "0xYourEvmAddress2"
# grpc-url = "https://your-operator-grpc-url2.com"

# Add more operators if needed

# Address of bitcoin multsig wallet
bitcoin-multisig = "tb1qqgnkrkhkeql9n2ear5z2c3t49496t6ca0r5ckj"
